services:
  - type: web
    name: kc-voice-assistant-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: KC_VOICE_ID
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true